#!/usr/bin/env python3
"""Apply a catalog-diff manifest to the working tree.

Reads the manifest YAML produced by main.py and performs the file
operations it declares: delete, create, and alias chain line-removal.
Comments in alias yaml files are preserved (ruamel.yaml round-trip).

Does NOT git commit / push — CI (or a human) handles that.

Usage:
    python scripts/catalog_diff/apply.py manifest.yaml
"""

import pathlib
import sys

import yaml
from ruamel.yaml import YAML

REPO = pathlib.Path(__file__).resolve().parents[2]
_ORDER = ["update_alias", "create_model", "delete_model"]


def apply_update_alias(action: dict) -> None:
    target = REPO / action["target"]
    before = action["before"]["chain"]
    after = action["after"]["chain"]
    removed = [m for m in before if m not in after]
    if not removed:
        return

    ry = YAML()
    ry.preserve_quotes = True
    # match the indent style of the existing alias yamls so the diff
    # is one line (the removed model) instead of N lines (all reflowed)
    ry.indent(mapping=2, sequence=4, offset=2)
    with target.open() as f:
        data = ry.load(f)
    chain = data.get("chain", [])
    for m in removed:
        while m in chain:
            chain.remove(m)
    with target.open("w") as f:
        ry.dump(data, f)


def apply_create_model(action: dict) -> None:
    target = REPO / action["target"]
    target.write_text(action["content"])


def apply_delete_model(action: dict) -> None:
    target = REPO / action["target"]
    if target.exists():
        target.unlink()


def write_pr_body(manifest: dict, out: pathlib.Path) -> None:
    summary = manifest.get("summary", {})
    actions = manifest.get("actions", [])
    lines = [
        "## Auto-detected catalog drift",
        "",
        f"**Source:** {manifest.get('source')}",
        f"**Generated:** {manifest.get('generated_at')}",
        "",
        "### Summary",
        f"- {summary.get('local_count', 0)} local -> {summary.get('remote_count', 0)} remote",
        f"- {summary.get('action_count', 0)} actions, {summary.get('warning_count', 0)} warnings",
        "",
        "### Changes",
    ]
    for a in actions:
        kind = a.get("kind", "?")
        if kind == "delete_model":
            refs = a.get("safety", {}).get("referenced_by_aliases") or []
            tail = f" (was in alias chain: {', '.join(refs)})" if refs else ""
            lines.append(f"- Delete `{a['model_id']}`{tail}")
        elif kind == "create_model":
            lines.append(f"- Create `{a['model_id']}`")
        elif kind == "update_alias":
            removed = [m for m in a["before"]["chain"] if m not in a["after"]["chain"]]
            lines.append(f"- Update alias `{a['alias']}`: remove {', '.join(removed)}")
    lines.append("")
    lines.append("Generated by `scripts/catalog_diff` agent.")
    out.write_text("\n".join(lines) + "\n")


_APPLIERS = {
    "update_alias": apply_update_alias,
    "create_model": apply_create_model,
    "delete_model": apply_delete_model,
}


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: apply.py <manifest.yaml>", file=sys.stderr)
        return 2
    manifest = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text())
    actions = manifest.get("actions", [])

    for kind in _ORDER:
        for action in (a for a in actions if a.get("kind") == kind):
            _APPLIERS[kind](action)
            print(f"applied: {kind} {action.get('target', '')}", file=sys.stderr)

    write_pr_body(manifest, pathlib.Path("pr-body.md"))
    print("wrote pr-body.md", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
